version: '3.5'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: mongod --smallfiles # --quiet
  peer-tutor-api:
    environment:
      - AM_I_IN_A_DOCKER_CONTAINER=1
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    container_name: peer-tutor-api
    image: peer-tutor-api
    ports:
      - 5000:5000
  peer-tutor-ui:
    build:
      context: ./peer-tutor-ui/angular/
      dockerfile: Dockerfile-prd-dist
    image: peer-tutor-ui
    container_name: peer-tutor-ui
    ports:
      - 8083:80
networks:
  default:
   name: web_dev
