FROM python:3.6.3

# set working directory
RUN mkdir -p /usr/src/peer-tutor

COPY . /peer-tutor
WORKDIR /peer-tutor/peer-tutor-api
# add requirements
#ADD ./peer-tutor-api/requirements.txt /usr/src/app/requirements.txt

ENV AM_I_IN_A_DOCKER_CONTAINER = yes
# install requirements
RUN pip install -r requirements.txt




# run server
CMD python server.py -t
