version: '3.5'
services:
 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  ports:
   - 27017:27017
  command: mongod --smallfiles # --quiet
 peer-tutor-api:
    build:
      context: ../
      dockerfile: Dockerfile-dev
    ports:
     - 5000:5000
networks:
 default:
  name: web_dev
