version: '3.5'
services:
 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/usr/data/logs
  volumes:
   - ./data/db:/usr/data/db
   - ./data/logs:/usr/data/logs
  ports:
   - 27017:27017
  command: mongod --smallfiles --dbpath=/usr/data/db --logpath=/usr/data/logs/log.txt # --quiet
networks:
 default:
  name: web_dev
