swagger: "2.0"
info:
  description: This API lets you retrive, store and update testbed data.
  version: "1.0.0"
  title: TestBed REST API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "{{is_testing}}/api"


paths:
  /student/id/{studentID}:
    get:
      summary: returns a student
      operationId: student_driver.getStudent
      tags:
        - "student"
      description: |
        Get a student by passing the student ID
      produces:
      - application/json
      parameters:
      - in: path
        name: studentID
        description: student obj is returned
        required: true
        type: string
      responses:
        200:
          description: student obj
          schema:
            type: object
            items:
              type: object
              $ref: '#/definitions/student'
        400:
          description: bad input parameter
  /hello:
    get:
      summary: returns hello
      operationId: helloClass.testHello
      tags:
        - "helloClass"
      description: |
        Returns a simple hello
      produces:
      - application/json
      responses:
        200:
          description: hello obj
          schema:
            type: object
            items:
              type: object
              $ref: '#/definitions/hello'
        400:
          description: bad input parameter

definitions:

  hello:
    type: object
    properties:
      hello:
        type: string
        example: hello-string
  student:
    type: object
    properties:
      student_id:
        type: string
        example: 01
      student_name:
        type: string
        example: 'Bharath Baiju'
